# Generated by Django 3.1.5 on 2022-01-27 05:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='department',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Music Production', 'Music Production'), ('Software Development', 'Software Development'), ('Computer Gaming', 'Computer Gaming')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('German', 'German')], max_length=150, null=True),
        ),
    ]
