# Generated by Django 3.1.5 on 2022-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220127_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_interview', models.DateField(default='NA')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('', 'Other'), ('Java Developer', 'Java Developer'), ('Python Delveloper', 'Python Delveloper'), ('UI/UX Developer', 'UI/UX Developer'), ('.NET Developer', '.NET Developer')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('overall_performance', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
                ('programming_fundamentals', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
                ('oops_concepts', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
                ('framework_concepts', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
                ('restful_concepts', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
                ('databases', models.CharField(blank=True, choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
