# Generated by Django 3.1.5 on 2022-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220127_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
