# Generated by Django 3.1.5 on 2022-01-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220127_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='databases',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='framework_concepts',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='oops_concepts',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='overall_performance',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='programming_fundamentals',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='restful_concepts',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], max_length=100, null=True),
        ),
    ]
