# Generated by Django 3.1.5 on 2022-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220128_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='overall_performance',
            field=models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100),
        ),
    ]
