# Generated by Django 3.1.5 on 2022-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220128_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(choices=[('Java Developer', 'Java Developer'), ('Python Delveloper', 'Python Delveloper'), ('UI/UX Developer', 'UI/UX Developer'), ('.NET Developer', '.NET Developer'), ('iOS Developer', 'iOS Developer')], default=None, max_length=100),
        ),
    ]
