# Generated by Django 3.1.5 on 2022-01-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220128_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date_interview',
        ),
    ]
